### ISSUE TITLE
Os exemplos 3.1 e o 3.2 não funcionam mais! 

### ISSUE THREAD

**Issue by ghost** [michaelhenrique182/livro_angularjs_abordagem_pratica_objetiva#1]
Acredito que seja pela versão do angularJs que foi modificada, mas esse exemplo não funciona mais

**Comment by michaelhenrique182** [comment]
Bom dia,

Conforme orientado no livro, tópico 'Versão do Angular', a versão utilizada no livro foi a 1.2.22, refletindo no correto funcionamento dos exemplos para esta versão.

Não há garantias de portabilidade para outras versôes uma vez que isso dependerá do próprio framework.

Mesmo dito isto, verifique se todos os arquivos javascript necessários no exemplo estão no mesmo diretório da página html do exemplo.

Agradeço o feedback e compreensão.
